version: '2'
services:
  sencounter:
    container_name: sencounter
    image: sencounter
    links:
      - "redis:redis"
    ports: 
      - "80:80"
  redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - "redis:/data"
volumes:
  redis:
    driver: local
